version: '3.8'

services:
  backend:
    image: kotpilota/ids_backend:latest
    restart: always
    volumes:
      - ./files:/app/files
      - ./data:/app/data
      - static_data:/app/static
    env_file: .env
    expose:
      - "80"
    environment:
      - PYTHONPATH=/app

  nginx:
    image: kotpilota/ids_nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - static_data:/static
    depends_on:
      - backend

volumes:
  static_data: