version: '3.8'

services:
  backend:
    image: kotpilota/ids_backend:latest
    restart: always
    volumes:
      - ./files:/app/files
      - ./data:/app/data
      - ./backend/app/app/static:/app/static  # Укажите точный путь к статическим файлам
    env_file: .env
    expose:
      - "80"

  nginx:
    image: kotpilota/ids_nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend/app/app/static:/static  # Используйте тот же путь
    depends_on:
      - backend