version: '3.8'

volumes:
  ids_static:
  ids_media:
  ids_data:

services:
  backend:
    image: kotpilota/ids_backend:latest
    restart: always
    volumes:
      - ids_static:/app/static
      - ids_media:/app/files
      - ids_data:/app/data
    env_file: .env
    expose:
      - "80"

  nginx:
    image: kotpilota/ids_nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ids_static:/static
      - ids_media:/media
    depends_on:
      - backend